# Generated by Django 5.2.17 on 2026-09-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('diretor', models.CharField(max_length=100)),
                ('estudio', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('ACA', 'Ação'), ('COM', 'Comédia'), ('DRA', 'Drama'), ('TER', 'Terror'), ('ANI', 'Animação')], default='DRA', max_length=3)),
                ('sinopse', models.TextField(blank=True)),
                ('duracao_minutos', models.IntegerField()),
                ('data_lancamento', models.DateField()),
                ('assistido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
